<?php

namespace DoctrineORMModule\Proxy\__CG__\SONUser\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Materia extends \SONUser\Entity\Materia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'id', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'titulo', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'urlMateria', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'conteudo', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'status', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'autor', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'revisor', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'publicador', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'sessao', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'updatedAt', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'createdAt');
        }

        return array('__isInitialized__', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'id', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'titulo', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'urlMateria', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'conteudo', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'status', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'autor', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'revisor', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'publicador', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'sessao', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'updatedAt', '' . "\0" . 'SONUser\\Entity\\Materia' . "\0" . 'createdAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Materia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlMateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlMateria', array());

        return parent::getUrlMateria();
    }

    /**
     * {@inheritDoc}
     */
    public function getConteudo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConteudo', array());

        return parent::getConteudo();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getAutor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutor', array());

        return parent::getAutor();
    }

    /**
     * {@inheritDoc}
     */
    public function getRevisor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevisor', array());

        return parent::getRevisor();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicador', array());

        return parent::getPublicador();
    }

    /**
     * {@inheritDoc}
     */
    public function getSessao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSessao', array());

        return parent::getSessao();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlMateria($urlMateria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlMateria', array($urlMateria));

        return parent::setUrlMateria($urlMateria);
    }

    /**
     * {@inheritDoc}
     */
    public function setConteudo($conteudo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConteudo', array($conteudo));

        return parent::setConteudo($conteudo);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setAutor($autor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutor', array($autor));

        return parent::setAutor($autor);
    }

    /**
     * {@inheritDoc}
     */
    public function setRevisor($revisor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevisor', array($revisor));

        return parent::setRevisor($revisor);
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicador($publicador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicador', array($publicador));

        return parent::setPublicador($publicador);
    }

    /**
     * {@inheritDoc}
     */
    public function setSessao($sessao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSessao', array($sessao));

        return parent::setSessao($sessao);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
