
<h3>Notícias</h3>
<br />

<form id="target" class="navbar-form navbar-left">
    <div class="row">
        <div class="span2"> </div>
        <div class="span8">
            <input type="text" class="form-control" id="search-view" name="search-view" placeholder="Search"/>
        </div>
    </div>
</form>
<br /> <br />
<div class="row">

<?php foreach($this->data as $entity): ?>
	<div class="col-md-12 post-single">
		<div class="heading-title">
			<h4>
				<a href="<?php echo $this->url('sonuser-public-list-materia/default',
                    array('controller'=>'noticias','action'=>'artigo','id'=>$entity->getUrlMateria()));?>">
				    <?php echo $entity->getTitulo(); ?>
				</a>
			</h4>
		</div>
		<div class="post-meta">
			<span>
			     <em>By <a href="#"><?php echo $entity->getAutor(); ?></a></em>
			</span>
			<span>
			     <em>On <?php echo $this->dateFormat( $entity->getCreatedAt(),
                                                      IntlDateFormatter::SHORT,
                                                      IntlDateFormatter::SHORT,
                                                      "pt_BR"
                                                     ); ?>
                 </em>
			</span>
			<span>
			     <em>In
			         <a href="<?php echo $this->url('sonuser-public-list-materia/default',
			                                  array('controller'=>'noticias',
			                                        'action'=>'categoria',
			                                        'id' => $entity->getSessao()->getNome()
			         )); ?>"><?php echo $entity->getSessao()->getNome(); ?></a>
			     </em>
			</span>
		</div>

		<p> <?php echo substr(strip_tags($entity->getConteudo()), 0, 600);?>...</p>
		<p><a class="btn btn-success" href="<?php echo $this->url('sonuser-public-list-materia/default',
                    array('controller'=>'noticias','action'=>'artigo','id'=>$entity->getUrlMateria()));?>" target="_self">Continue Lendo »</a></p>
	</div>

<?php endforeach; ?>

</div>

<?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>

<script type="text/javascript">
$( "#target" ).submit(function( event ) {
  var urlSearch = "<?php echo $this->url('sonuser-public-list-materia/default', array('controller'=>'noticias','action'=>'search')); ?>";
  var search = $( "#search-view" ).val();
  if (search != "") {
	var keySearch = '\\'+search;
	window.location.replace(urlSearch.concat(keySearch));
  }
  event.preventDefault();
});
</script>