<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SONBase\Service\AbstractService'   => __DIR__ . '/src/SONBase/Service/AbstractService.php',
    'SONBase\Mail\Mail'                 => __DIR__ . '/src/SONBase/Mail/Mail.php',
    'SONBase\Controller\CrudController' => __DIR__ . '/src/SONBase/Controller/CrudController.php',
    'SONBase\Module'                    => __DIR__ . '/Module.php',
);
