<h1>Capas</h1>

<br />

<p>
    <a href="<?php echo $this->url('sonuser-capa-materia/default',array('action'=>'new')); ?>">Novo</a>
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Titulo</th>
        <th>Usuário</th>
        <th>Capa Principal</th>
        <th>Capa Secundário</th>
        <th>Ação</th>
    </tr>

    <?php foreach($this->data as $entity): ?>
    <tr>
        <td><?php echo $entity->getId(); ?></td>
        <td><?php echo $entity->getMateria()->getTitulo(); ?></td>
        <td><?php echo $entity->getUsuario()->getNome(); ?></td>
        <td><?php echo $entity->getCapaPrincipal() == 1 ? "Sim" : "Não" ?></td>
        <td><?php echo $entity->getAtivo() == 1 ? "Sim" : "Não" ?></td>
        <td>
            <a href="<?php echo $this->url('sonuser-capa-materia/default',
                    array('controller'=>'capa','action'=>'edit','id'=>$entity->getId()));?>">Editar</a>

            <a href="<?php echo $this->url('sonuser-capa-materia/default',
                    array('controller'=>'capa','action'=>'delete','id'=>$entity->getId()));?>">Delete</a>

        </td>
    </tr>
    <?php endforeach; ?>
</table>
<br />

<?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>