<h1>Materias</h1>

<br />
<form id="target" class="navbar-form navbar-left">
    <div class="row">
        <div class="span3">
                <p>
                  <a href="<?php echo $this->url('sonuser-materia/default',array('action'=>'new')); ?>">Novo</a>
                </p>
        </div>
        <div class="span8">
            <input type="text" class="form-control" id="search-view" name="search-view" placeholder="Search"/>
        </div>
    </div>
</form>
<br /> <br />
<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Autor</th>
        <th>Revisor</th>
        <th>Publicador</th>
        <th>Status</th>
        <th>Ação</th>
    </tr>

    <?php foreach($this->data as $entity): ?>
    <tr>
        <td><?php echo $entity->getId(); ?></td>
        <td><?php echo $entity->getTitulo(); ?></td>
        <td><?php echo $entity->getAutor(); ?></td>
        <td><?php echo $entity->getRevisor(); ?></td>
        <td><?php echo $entity->getPublicador(); ?></td>
        <td><?php echo $entity->getStatus(); ?></td>
        <td>
            <a href="<?php echo $this->url('sonuser-materia/default',
                    array('controller'=>'materias','action'=>'edit','id'=>$entity->getId()));?>">Editar</a>

            <a href="<?php echo $this->url('sonuser-materia/default',
                    array('controller'=>'materias','action'=>'delete','id'=>$entity->getId()));?>">Delete</a>

        </td>
    </tr>
    <?php endforeach; ?>
</table>
<br />

<?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>

<script type="text/javascript">
$( "#target" ).submit(function( event ) {
  var urlSearch = "<?php echo $this->url('sonuser-materia/default', array('controller'=>'materias','action'=>'search')); ?>";
  var search = $( "#search-view" ).val();
  if (search != "") {
	var keySearch = '\\'+search;
	window.location.replace(urlSearch.concat(keySearch));
  }
  event.preventDefault();
});
</script>