<?php if ($this->capa != null) :?>
<div class="hero-unit">
    <h1>
       <a href="<?php echo $this->url('sonuser-public-list-materia/default',
                      array('controller'=>'noticias','action'=>'artigo','id'=>$this->capa->getMateria()->getUrlMateria()));?>">
        <?php echo sprintf($this->translate($this->capa->getMateria()->getTitulo()), '<span class="zf-green">', '</span>') ?>
        </a>
    </h1>
    <p><?php echo substr(strip_tags($this->capa->getMateria()->getConteudo()), 0, 250); ?></p>
    <p><a class="btn btn-success btn-large" href="<?php echo $this->url('sonuser-public-list-materia/default',
                                                        array('controller'=>'noticias',
                                                              'action'=>'artigo',
                                                            'id'=>$this->capa->getMateria()->getUrlMateria()));?>" target="_self">
            <?php echo $this->translate('Leia Mais') ?> &raquo;
       </a>
     </p>
</div>
<?php endif;?>

<div class="row">

<?php if ($this->subCapa != null) :?>
    <?php foreach($this->subCapa as $subCapa): ?>
        <div class="span4">
            <h2><?php echo substr(strip_tags($subCapa->getMateria()->getTitulo()), 0, 35) ?>..</h2>
            <p><?php echo substr(strip_tags($subCapa->getMateria()->getConteudo()), 0, 200); ?></p>
            <p><a class="btn btn-success" href="<?php echo $this->url('sonuser-public-list-materia/default',
                                                        array('controller'=>'noticias',
                                                              'action'=>'artigo',
                                                              'id'=> $subCapa->getMateria()->getUrlMateria()));?>" target="_self">
                    <?php echo $this->translate('Leia Mais') ?> &raquo;
               </a>
            </p>
        </div>
    <?php endforeach; ?>
<?php endif;?>
</div>